(() => {
  const PHONE='218913442640';
  const TEXT={
    en:{digitalMenu:'THE DIGITAL MENU ✳ TRIPOLI',colorTheme:'Theme',chooseTheme:'Choose a mood',backSite:'Back to site',eyebrow:'A MENU TO EXPLORE',readerHint:'TAP THE ARROWS OR SWIPE TO TURN THE PAGE',previous:'PREVIOUS',next:'NEXT PAGE',sampleNotice:'CONCEPT MENU • ITEMS AND PRICES ARE EXAMPLES',basket:'YOUR BASKET',yourOrder:'YOUR ORDER',basketTitle:'Good choice.',emptyTitle:'Your basket is empty.',emptyDesc:'Turn a page and find something delicious.',browseBook:'Browse the menu',nameLabel:'Your name (optional)',namePlaceholder:'What shall we call you?',methodLabel:'HOW WOULD YOU LIKE IT?',pickup:'Pickup',delivery:'Delivery inquiry',notesLabel:'Notes (optional)',notesPlaceholder:'Special requests or delivery address...',total:'ESTIMATED TOTAL',totalNotice:'Sample prices. مطعم العيلة will confirm availability and final cost on WhatsApp.',orderWhatsApp:'SEND ON WHATSAPP',waFallbackTitle:'Open WhatsApp',waFallbackDesc:'This embedded preview may block external links. Copy this link and paste it in your browser to open WhatsApp.',copyLink:'Copy WhatsApp link',copied:'WhatsApp link copied',copyManually:'Select and copy the link above',added:'Added to your basket',remove:'Remove',currency:'LYD',add:'Add',page:'PAGE',dishes:'DISHES',
      cover:'Welcome',starters:'To start',classics:'Libyan classics',grill:'From the grill',drinks:'Something to sip',finish:'The last page',
      coverEyebrow:'PULL UP A CHAIR',coverTitle:'Every meal<br>is a <em>story.</em>',coverDesc:'Come in hungry. Stay a little longer. Turn the pages to find the food that brings us all together.',coverCue:'TURN THE PAGE TO EXPLORE',coverBig:'EAT<br>WELL.',coverCaption:'THE FAMILY TABLE',coverMeta:'FAMILY FOOD · TRIPOLI SOUL',
      startersEyebrow:'01 / SMALL PLATES',startersTitle:'The first<br><em>hello.</em>',startersDesc:'Little bites made for passing around the table. The best way to begin.',startersCaption:'START WITH SOMETHING GOOD',startersQuote:'A little something for everyone at the table.',
      classicsEyebrow:'02 / HOUSE FAVOURITES',classicsTitle:'From our<br><em>kitchen.</em>',classicsDesc:'Comforting Libyan flavours, cooked with patience and served with heart.',classicsCaption:'THE GOOD OLD FAVOURITES',classicsQuote:'The dishes we keep coming back to.',
      grillEyebrow:'03 / FROM THE GRILL',grillTitle:'Fire &<br><em>flavour.</em>',grillDesc:'The kind of food that arrives sizzling and disappears quickly.',grillCaption:'MADE TO SHARE',grillQuote:'More plates, more stories, more time together.',
      drinksEyebrow:'04 / SOMETHING TO SIP',drinksTitle:'One more<br><em>cup?</em>',drinksDesc:'Because a good meal deserves a slow ending.',drinksCaption:'STAY A LITTLE LONGER',drinksQuote:'The table is never in a hurry.',
      finishEyebrow:'UNTIL NEXT TIME',finishTitle:'One table.<br><em>All of us.</em>',finishDesc:'Found your favourites? Add them to your basket and send your order to مطعم العيلة on WhatsApp.',finishCaption:'SEE YOU AT THE TABLE',finishButton:'OPEN YOUR BASKET',finishContact:'TRIPOLI, LIBYA',finishPhone:'CALL OR WHATSAPP',footnote:'Sample menu & prices for design preview. Ask our team for availability.',themeNames:['Rouge Maison','Obsidian Gold','Emerald','Royal Plum','Sapphire','Champagne']},
    ar:{digitalMenu:'القائمة الرقمية ✳ طرابلس',colorTheme:'الألوان',chooseTheme:'اختر الأجواء',backSite:'العودة للموقع',eyebrow:'قائمة تستحق الاكتشاف',readerHint:'استخدم الأسهم أو اسحب لتقليب الصفحات',previous:'السابق',next:'الصفحة التالية',sampleNotice:'قائمة تجريبية • الأطباق والأسعار إرشادية',basket:'سلّتك',yourOrder:'طلبك',basketTitle:'اختيار موفق.',emptyTitle:'سلّتك فارغة.',emptyDesc:'قلّب الصفحة واختر ما تحب.',browseBook:'تصفّح القائمة',nameLabel:'اسمك (اختياري)',namePlaceholder:'بأي اسم نناديك؟',methodLabel:'كيف تريد استلام طلبك؟',pickup:'استلام من المطعم',delivery:'استفسار عن التوصيل',notesLabel:'ملاحظات (اختياري)',notesPlaceholder:'طلبات خاصة أو عنوان التوصيل...',total:'المجموع التقريبي',totalNotice:'الأسعار إرشادية. يؤكد مطعم العيلة توفر الأطباق والتكلفة النهائية عبر واتساب.',orderWhatsApp:'أرسل عبر واتساب',waFallbackTitle:'افتح واتساب',waFallbackDesc:'قد يمنع العرض المدمج فتح الروابط الخارجية. انسخ الرابط والصقه في متصفحك لفتح واتساب.',copyLink:'نسخ رابط واتساب',copied:'تم نسخ رابط واتساب',copyManually:'حدّد الرابط أعلاه وانسخه يدوياً',added:'أُضيف إلى سلّتك',remove:'حذف',currency:'د.ل',add:'أضف',page:'صفحة',dishes:'أطباق',
      cover:'أهلاً',starters:'مقبلات',classics:'أطباق ليبية',grill:'مشاوي',drinks:'مشروبات',finish:'إلى اللقاء',
      coverEyebrow:'نورتونا',coverTitle:'كل سفرة<br>لها <em>حكاية.</em>',coverDesc:'تعالوا جوعانين، وخذوا راحتكم. قلّبوا الصفحات واختاروا النكهات اللي تجمعنا.',coverCue:'قلّب الصفحة واكتشف',coverBig:'أكل<br>طيّب.',coverCaption:'سفرة العائلة',coverMeta:'أكل العائلة · بروح طرابلس',
      startersEyebrow:'٠١ / المقبلات',startersTitle:'بداية<br><em>طيّبة.</em>',startersDesc:'لقيمات خفيفة تحلى بالمشاركة، وأحلى بداية للسفرة.',startersCaption:'بداية تستحق اللّمة',startersQuote:'للجميع على سفرتنا نصيب.',
      classicsEyebrow:'٠٢ / من مطبخنا',classicsTitle:'نكهات<br><em>الدار.</em>',classicsDesc:'أطباق ليبية أصيلة، تُحضّر على مهل وتُقدّم بمحبة.',classicsCaption:'أطباق نحبها جميعاً',classicsQuote:'نكهات ترجعنا دائماً للبيت.',
      grillEyebrow:'٠٣ / المشاوي',grillTitle:'طعم<br><em>النار.</em>',grillDesc:'مشاوي تفتح النفس وتجمع الكل حول السفرة.',grillCaption:'للّمة والمشاركة',grillQuote:'أطباق أكثر، حكايات أكثر، ولمّة أطول.',
      drinksEyebrow:'٠٤ / المشروبات',drinksTitle:'كوب<br><em>زيادة؟</em>',drinksDesc:'لأن الأكل الطيّب يستحق ختاماً على راحتنا.',drinksCaption:'اقعدوا شوية أكثر',drinksQuote:'السفرة ما تستعجل أحد.',
      finishEyebrow:'إلى اللقاء',finishTitle:'سفرة وحدة.<br><em>للجميع.</em>',finishDesc:'اخترت أطباقك؟ أضفها إلى السلة وأرسل طلبك إلى مطعم العيلة عبر واتساب.',finishCaption:'نشوفوكم على السفرة',finishButton:'افتح سلّتك',finishContact:'طرابلس، ليبيا',finishPhone:'اتصال أو واتساب',footnote:'قائمة وأسعار تجريبية. اسأل فريقنا عن التوفر.',themeNames:['أحمر الدار','الأسود والذهبي','زمردي','برقوقي ملكي','ياقوتي','شامبانيا']}
  };
  const DISHES=[
    {id:'brik',cat:'starters',price:16,image:'dish-brik.jpg',en:'Crispy Brik',ar:'بريك مقرمش',descEn:'Golden pastry parcels, lemon & fresh herbs.',descAr:'رقائق ذهبية مقرمشة مع الليمون والأعشاب.'},
    {id:'salad',cat:'starters',price:18,image:'dish-salad.jpg',en:'Garden Salad',ar:'سلطة الدار',descEn:'Fresh vegetables, herbs & olive oil.',descAr:'خضار طازجة وأعشاب وزيت زيتون.'},
    {id:'couscous',cat:'classics',price:42,image:'dish-couscous.jpg',en:'Lamb Couscous',ar:'كسكسي باللحم',descEn:'Fluffy couscous, lamb & seasonal vegetables.',descAr:'كسكسي مفوّر، لحم طري وخضار موسمية.'},
    {id:'bazin',cat:'classics',price:38,image:'dish-bazin.jpg',en:'Traditional Bazin',ar:'بازين ليبي',descEn:'A Libyan classic with rich tomato lamb sauce.',descAr:'طبق ليبي أصيل بمرقة الطماطم واللحم.'},
    {id:'rishta',cat:'classics',price:34,image:'dish-rishta.jpg',en:'Libyan Rishta',ar:'رشتة ليبية',descEn:'Slow-cooked noodles, chickpeas & spiced sauce.',descAr:'رشتة مطبوخة على مهل بالحمص والمرقة المتبّلة.'},
    {id:'mbakbaka',cat:'classics',price:36,image:'dish-mbakbaka.jpg',en:'Mbakbaka',ar:'مبكبكة',descEn:'Comforting pasta in a fragrant tomato broth.',descAr:'مكرونة بمرقة الطماطم الغنية والنكهات الليبية.'},
    {id:'grill',cat:'grill',price:45,image:'dish-grill.jpg',en:'Mixed Grill',ar:'مشاوي مشكلة',descEn:'Flame-kissed skewers, bread & house sauces.',descAr:'أسياخ مشوية، خبز طازج وصلصات البيت.'},
    {id:'tea',cat:'drinks',price:9,image:'dish-tea.jpg',en:'Mint Tea',ar:'شاي بالنعناع',descEn:'A little sweetness, poured the traditional way.',descAr:'شاي بالنعناع على الطريقة التقليدية.'}
  ];
  const CHAPTERS=[{id:'cover',img:'hero-feast.jpg'},{id:'starters',img:'dish-brik.jpg'},{id:'classics',img:'dish-couscous.jpg'},{id:'grill',img:'dish-grill.jpg'},{id:'drinks',img:'dish-tea.jpg'},{id:'finish',img:'family-table.jpg'}];
  const THEMES=[{id:'rouge',hex:'#a5342b'},{id:'obsidian',hex:'#202927'},{id:'emerald',hex:'#1f6755'},{id:'plum',hex:'#76385d'},{id:'sapphire',hex:'#245b78'},{id:'champagne',hex:'#8c6b40'}];
  const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
  const stored=(key,fallback)=>{try{return localStorage.getItem(key)||fallback;}catch{return fallback;}};
  const save=(key,val)=>{try{localStorage.setItem(key,val);}catch{}};
  let lang=stored('albay-lang',navigator.language?.startsWith('ar')?'ar':'en');if(!TEXT[lang])lang='en';
  let theme=stored('albay-theme','rouge');if(!THEMES.some(t=>t.id===theme))theme='rouge';
  let index=Math.max(0,CHAPTERS.findIndex(x=>x.id===location.hash.slice(1)));let animating=false;let cart={};
  try{const data=JSON.parse(stored('albay-cart','{}'));if(data&&typeof data==='object'&&!Array.isArray(data))for(const [id,n] of Object.entries(data))if(DISHES.some(d=>d.id===id)&&Number.isInteger(n)&&n>0&&n<=99)cart[id]=n;}catch{}
  const t=k=>TEXT[lang][k]||k, money=n=>`${n} ${t('currency')}`;
  const count=()=>Object.values(cart).reduce((a,n)=>a+n,0),total=()=>DISHES.reduce((a,d)=>a+(cart[d.id]||0)*d.price,0);
  const name=d=>d[lang],desc=d=>d[lang==='ar'?'descAr':'descEn'];
  function renderThemeChoices(){$('#themeChoices').innerHTML=THEMES.map((x,i)=>`<button class="theme-choice" data-theme-choice="${x.id}" type="button"><span class="swatch" style="background:${x.hex}"></span><span>${t('themeNames')[i]}</span><span class="chosen">${x.id===theme?'✓':''}</span></button>`).join('');}
  function renderChapters(){$('#chapterNav').innerHTML=CHAPTERS.map((c,i)=>`<button type="button" class="chapter-tab ${i===index?'active':''}" data-chapter="${i}" aria-current="${i===index?'page':'false'}"><span class="tab-no">${String(i+1).padStart(2,'0')}</span>${t(c.id)}</button>`).join('');$('#navProgress').innerHTML=CHAPTERS.map((c,i)=>`<button class="progress-step ${i===index?'active':''}" data-chapter="${i}" type="button" aria-label="${t(c.id)}"></button>`).join('');$('#chapterNav .active')?.scrollIntoView({block:'nearest',inline:'nearest'});}
  function renderDishes(cat){const items=DISHES.filter(x=>x.cat===cat);return `<div class="category-subhead"><span>${t('dishes')}</span><span>${String(items.length).padStart(2,'0')}</span></div><div class="dish-list">${items.map(d=>`<article class="book-dish"><img src="assets/${d.image}" alt="" loading="lazy"/><div class="dish-main"><h3>${name(d)}</h3><p>${desc(d)}</p></div><div class="dish-action"><strong dir="ltr">${money(d.price)}</strong><button type="button" data-add="${d.id}" aria-label="${t('add')} ${name(d)}">+</button></div></article>`).join('')}</div><p class="page-footnote">${t('footnote')}</p>`;}
  function renderPage(){
    const c=CHAPTERS[index];$('#bookPhoto').src=`assets/${c.img}`;$('#bookPhoto').alt=t(`${c.id}Caption`);$('#photoCaption').textContent=`${String(index+1).padStart(2,'0')} / ${t(`${c.id}Caption`)}`;
    let html='';
    if(c.id==='cover') html=`<div class="cover-main"><div><span class="page-eyebrow">${t('coverEyebrow')}</span><h1>${t('coverTitle')}</h1><p class="page-lead">${t('coverDesc')}</p><div class="cover-line"></div><div class="cover-big">${t('coverBig')}</div></div><div><div class="cover-meta"><span>${t('coverMeta')}</span><strong>✳</strong></div><div class="cover-cue">${t('coverCue')} <span aria-hidden="true">↗</span></div></div></div>`;
    else if(c.id==='finish') html=`<div class="end-main"><div><span class="page-eyebrow">${t('finishEyebrow')}</span><h2>${t('finishTitle')}</h2><p>${t('finishDesc')}</p><button class="primary-button" type="button" data-open-cart>${t('finishButton')} <span>↗</span></button></div><div class="end-contact"><span>${t('finishContact')}</span><span>${t('finishPhone')}<br><strong dir="ltr">+218 91 344 2640</strong></span></div></div>`;
    else html=`<span class="page-eyebrow">${t(`${c.id}Eyebrow`)}</span><h2>${t(`${c.id}Title`)}</h2><p class="page-lead">${t(`${c.id}Desc`)}</p>${renderDishes(c.id)}${c.id==='classics'?'':`<div class="feature-quote">✳ &nbsp;${t(`${c.id}Quote`)}</div>`}`;
    $('#pageContent').innerHTML=html;$('#pageContent').scrollTop=0;
    $('#pageNumber').textContent=`${String(index+1).padStart(2,'0')} / ${String(CHAPTERS.length).padStart(2,'0')}`;$('#chapterCounter').textContent=$('#pageNumber').textContent;
    $('#prevPage').disabled=index===0;$('#nextPage').disabled=index===CHAPTERS.length-1;
    $('#prevPage>span:first-child').textContent=lang==='ar'?'→':'←';$('#nextPage>span:last-child').textContent=lang==='ar'?'←':'→';
    renderChapters();
  }
  function turnTo(next){if(animating||next<0||next>=CHAPTERS.length||next===index)return;const sheet=$('#bookSheet');if(matchMedia('(prefers-reduced-motion: reduce)').matches){index=next;renderPage();updateHash();return;}animating=true;const direction=next>index?'forward':'backward';sheet.classList.add('turn-out',direction);setTimeout(()=>{index=next;renderPage();updateHash();sheet.classList.remove('turn-out');sheet.classList.add('turn-in');requestAnimationFrame(()=>requestAnimationFrame(()=>{sheet.classList.remove('turn-in');setTimeout(()=>{sheet.classList.remove(direction);animating=false;},300);}));},260);}
  function updateHash(){history.replaceState(null,'',index===0?location.pathname:`#${CHAPTERS[index].id}`);}
  function translate(){document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';document.title=lang==='ar'?'مطعم العيلة — قائمة الطعام':'مطعم العيلة — The Menu';$('#languageValue').textContent=lang.toUpperCase();$$('[data-t]').forEach(el=>el.textContent=t(el.dataset.t));$$('[data-placeholder]').forEach(el=>el.placeholder=t(el.dataset.placeholder));renderThemeChoices();renderPage();renderCart();}
  function toast(text){let el=$('#readerToast');el.textContent=text;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),1800);}
  function sendLink(){const mode=$('input[name=orderMethod]:checked')?.value||'pickup',guest=$('#guestName').value.trim(),notes=$('#guestNotes').value.trim(),parts=DISHES.filter(d=>cart[d.id]).map(d=>`• ${name(d)} × ${cart[d.id]} — ${money(d.price*cart[d.id])}`);let msg= count()===0?(lang==='ar'?'مرحباً مطعم العيلة، أود الاستفسار عن المطعم.':'Hello مطعم العيلة, I would like to ask about the restaurant.'):(lang==='ar'?['مرحباً مطعم العيلة، أود طلب:',...parts,`المجموع التقريبي: ${money(total())}`,`الطريقة: ${mode==='pickup'?'استلام من المطعم':'استفسار عن التوصيل'}`,guest?`الاسم: ${guest}`:'',notes?`ملاحظات: ${notes}`:'','يرجى تأكيد التوفر والسعر النهائي.']:['Hello مطعم العيلة! I would like to order:',...parts,`Estimated subtotal: ${money(total())}`,`Method: ${mode==='pickup'?'Pickup':'Delivery inquiry'}`,guest?`Name: ${guest}`:'',notes?`Notes: ${notes}`:'','Please confirm availability and final price.']).filter(Boolean).join('\n');let url=`https://wa.me/${PHONE}?text=${encodeURIComponent(msg)}`;$('#sendOrder').href=url;$('#quickWhatsApp').href=url;}
  function renderCart(){let n=count();$('#basketCount').textContent=n;$('#emptyState').hidden=n>0;$('#filledState').hidden=n===0;$('#drawerBottom').hidden=n===0;$('#orderTotal').textContent=money(total());$('#orderItems').innerHTML=DISHES.filter(d=>cart[d.id]).map(d=>`<div class="order-item"><img src="assets/${d.image}" alt=""/><div><div class="order-item-name"><span>${name(d)}</span><span dir="ltr">${money(cart[d.id]*d.price)}</span></div><div class="order-item-controls"><div class="quantity"><button type="button" data-qty="${d.id}" data-step="-1" aria-label="− ${name(d)}">−</button><span>${cart[d.id]}</span><button type="button" data-qty="${d.id}" data-step="1" aria-label="+ ${name(d)}">+</button></div><button class="remove" type="button" data-remove="${d.id}">${t('remove')}</button></div></div></div>`).join('');sendLink();}
  function changeCart(id,delta){cart[id]=Math.min(99,Math.max(0,(cart[id]||0)+delta));if(!cart[id])delete cart[id];save('albay-cart',JSON.stringify(cart));renderCart();}
  function openCart(){$('#drawerShade').hidden=false;$('#orderDrawer').classList.add('open');$('#orderDrawer').setAttribute('aria-hidden','false');document.body.classList.add('locked');$('#closeDrawer').focus();}
  function closeCart(){$('#drawerShade').hidden=true;$('#orderDrawer').classList.remove('open');$('#orderDrawer').setAttribute('aria-hidden','true');if($('#waFallback').hidden)document.body.classList.remove('locked');}
  function showWaFallback(url){$('#waUrl').value=url;$('#waShade').hidden=false;$('#waFallback').hidden=false;document.body.classList.add('locked');$('#waUrl').focus();$('#waUrl').select();}
  function closeWaFallback(){$('#waShade').hidden=true;$('#waFallback').hidden=true;if(!$('#orderDrawer').classList.contains('open'))document.body.classList.remove('locked');}
  function setup(){document.body.dataset.theme=theme;translate();
    $('#languageButton').addEventListener('click',()=>{lang=lang==='en'?'ar':'en';save('albay-lang',lang);translate();});
    $('#paletteButton').addEventListener('click',()=>{let show=$('#paletteDropdown').hidden;$('#paletteDropdown').hidden=!show;$('#paletteButton').setAttribute('aria-expanded',String(show));});
    $('#themeChoices').addEventListener('click',e=>{let btn=e.target.closest('[data-theme-choice]');if(!btn)return;theme=btn.dataset.themeChoice;document.body.dataset.theme=theme;save('albay-theme',theme);renderThemeChoices();$('#paletteDropdown').hidden=true;$('#paletteButton').setAttribute('aria-expanded','false');});
    document.addEventListener('click',e=>{if(!e.target.closest('.theme-control')){$('#paletteDropdown').hidden=true;$('#paletteButton').setAttribute('aria-expanded','false');}let btn=e.target.closest('[data-chapter]');if(btn)turnTo(Number(btn.dataset.chapter));});
    $('#prevPage').addEventListener('click',()=>turnTo(index-1));$('#nextPage').addEventListener('click',()=>turnTo(index+1));
    let startX=0,startY=0;$('#bookSheet').addEventListener('touchstart',e=>{startX=e.changedTouches[0].clientX;startY=e.changedTouches[0].clientY;},{passive:true});$('#bookSheet').addEventListener('touchend',e=>{let dx=e.changedTouches[0].clientX-startX,dy=e.changedTouches[0].clientY-startY;if(Math.abs(dx)>65&&Math.abs(dx)>Math.abs(dy)*1.4)turnTo(index+((dx<0)===(lang==='en')?1:-1));},{passive:true});
    document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeWaFallback();closeCart();$('#paletteDropdown').hidden=true;}if(['ArrowLeft','ArrowRight'].includes(e.key)&&!$('#orderDrawer').classList.contains('open')&&e.target.tagName!=='INPUT'&&e.target.tagName!=='TEXTAREA'){e.preventDefault();turnTo(index+((e.key==='ArrowRight')===(lang==='en')?1:-1));}});
    $('#pageContent').addEventListener('click',e=>{let btn=e.target.closest('[data-add]');if(btn){changeCart(btn.dataset.add,1);toast(t('added'));}if(e.target.closest('[data-open-cart]'))openCart();});
    $('#cartOpen').addEventListener('click',openCart);$('#closeDrawer').addEventListener('click',closeCart);$('#drawerShade').addEventListener('click',closeCart);$('#browseBook').addEventListener('click',closeCart);
    $('#orderItems').addEventListener('click',e=>{let remove=e.target.closest('[data-remove]');if(remove){delete cart[remove.dataset.remove];save('albay-cart',JSON.stringify(cart));renderCart();return;}let qty=e.target.closest('[data-qty]');if(qty)changeCart(qty.dataset.qty,Number(qty.dataset.step));});
    ['#guestName','#guestNotes'].forEach(sel=>$(sel).addEventListener('input',sendLink));$$('input[name=orderMethod]').forEach(el=>el.addEventListener('change',sendLink));
    document.addEventListener('click',e=>{let link=e.target.closest('a[href^="https://wa.me/"]');if(!link||window.self===window.top)return;e.preventDefault();let popup=window.open(link.href,'_blank');if(popup)popup.opener=null;else showWaFallback(link.href);});
    $('#closeWaFallback').addEventListener('click',closeWaFallback);$('#waShade').addEventListener('click',closeWaFallback);
    $('#copyWa').addEventListener('click',async()=>{let field=$('#waUrl'),copied=false;try{if(navigator.clipboard&&window.isSecureContext){await navigator.clipboard.writeText(field.value);copied=true;}}catch{}if(!copied){field.focus();field.select();try{copied=document.execCommand('copy');}catch{}}toast(t(copied?'copied':'copyManually'));});
    window.addEventListener('storage',e=>{if(e.key==='albay-cart'){try{cart=JSON.parse(e.newValue||'{}')||{};renderCart();}catch{}}});
  }
  setup();
})();
